version: "3.4"

services:
  dev:
    image: golang:1.15.2-buster
    volumes:
      - .:/work
      - graval-mod:/go/pkg/mod/
    working_dir: /work
    command: bash
    environment:
      GO111MODULE: "on"

volumes:
  graval-mod: ~
